
[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 11

[general]
import = [
    "~/.config/alacritty/themes/tokyo-night-alacritty-theme/tokyo-night.toml"
]
